version: '3'
services:
  meow-reminder:
    image: issymeow/meow-reminder:latest
    container_name: meow-reminder
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # ACHTUNG NEU: Wir mounten jetzt den GANZEN Ordner data
      # Das data.json File erstellt sich automatisch darin!
      - ./data:/app/data
      - ./uploads:/app/public/img/uploads
    environment:
      - TZ=Europe/Berlin
